# Generated by Django 4.1.5 on 2023-01-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=255)),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('publishDate', models.DateTimeField(auto_now_add=True)),
                ('pathMedia', models.FileField(upload_to='media/')),
                ('published', models.BooleanField(default=True)),
            ],
        ),
    ]
