# Generated by Django 4.1.5 on 2023-01-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pathMedia',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
