# Generated by Django 4.1.2 on 2022-12-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.IntegerField(auto_created=True, blank=True, null=True)),
                ('pseudo', models.CharField(default='', max_length=255)),
                ('lastname', models.CharField(default='', max_length=255)),
                ('firstname', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
                ('birthday', models.DateTimeField(auto_now=True)),
                ('idFaculty', models.IntegerField(blank=True, null=True)),
                ('createdAT', models.DateTimeField(auto_now=True)),
                ('updatedAT', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
