# Generated by Django 4.1.2 on 2022-12-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0002_remove_login_id_login_pathpp_alter_login_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='birthday',
            field=models.DateTimeField(default=False),
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(default=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='idUser',
            field=models.AutoField(auto_created=True, default=False, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='pseudo',
            field=models.CharField(default=False, max_length=255, unique=True),
        ),
    ]
