# Generated by Django 4.1.2 on 2022-12-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0004_alter_login_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='idUser',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
