# Generated by Django 4.1.2 on 2022-12-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0005_alter_login_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='login',
            name='idUser',
            field=models.AutoField(auto_created=True, default=False, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
