# Generated by Django 4.1.2 on 2022-12-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0006_alter_login_email_alter_login_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(default=False, max_length=255, unique=True),
        ),
    ]
