# Generated by Django 4.1.2 on 2022-12-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0007_alter_login_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='idUser',
            field=models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
