# Generated by Django 4.1.2 on 2022-12-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0008_alter_login_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='birthday',
            field=models.DateTimeField(default=''),
        ),
    ]
