# Generated by Django 4.1.2 on 2022-12-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0009_alter_login_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='birthday',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
